version: '3.8'

name: streamforge

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_streamforge
    ports:
      - "9000:9000"  #api port
      - "9001:9001" #console port
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - streamforge_network

  db:
    image: postgres:15
    container_name: psql_streamforge
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streamforge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - streamforge_network

  redis:
    image: redis:7-alpine
    container_name: redis_streamforge
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - streamforge_network

volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  streamforge_network:
    driver: bridge
