spring.application.name=streamforge

#h2 db config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#minio config
minio.url=http://localhost:9000
minio.access.name=minioadmin
minio.access.secret=minioadmin
minio.bucket.name=streamforge-media
minio.bucket.chunk=streamforge-chunk